Update README.md
lorenzoh/DataAugmentation.jl pull request #92
Opened 2024-06-28 07:56 UTC by isentropic

direct to the working link

2024-06-28 12:30 UTC, adrhill requested changes

2024-06-28 12:30 UTC, adrhill commented on README.md
> +[Documentation | Latest]([https://fluxml.github.io/DataAugmentation.jl/dev/documents/README.md](https://fluxml.ai/DataAugmentation.jl/dev/))
I don't think we need to keep the broken URL around:
```suggestion
[Documentation | Latest](https://fluxml.ai/DataAugmentation.jl/dev/)
```

2024-06-28 12:30 UTC, adrhill commented on README.md
>  ![compat](https://github.com/FluxML/DataAugmentation.jl/actions/workflows/CompatHelper/badge.svg)
While we're at it, we could also fix the badges:

```suggestion
 ![compat](https://github.com/FluxML/DataAugmentation.jl/actions/workflows/CompatHelper.yml/badge.svg)
```

and in the line above:
```md
![CI](https://github.com/FluxML/DataAugmentation.jl/actions/workflows/ci.yml/badge.svg)
```

2024-07-01 04:34 UTC, isentropic commented
right

2024-07-01 04:53 UTC, CarloLucibello approved these changes

2024-07-01 20:35 UTC, adrhill approved these changes

2024-07-01 20:37 UTC, merged

2024-07-01 20:38 UTC, adrhill commented
Thanks! :)